## collections.counter()

In [5]:
from collections import Counter

n = int(input()) # number of shoes
s = list(map(int, input().split())) # list of sizes of shoes
s = Counter(s)
N = int(input()) # number of cutomers

total_money = 0

for i in range(N):  # loop over the desired size and prices
    d_size, price = input().split()
    d_size = int(d_size)
    price = int(price)

    if d_size in s.keys():
        if s[d_size] != 0:
            total_money += price
            s[d_size] -= 1
            
print(total_money)

200


## DefaultDict Tutorial

In [1]:
from collections import defaultdict

A ,B = list(map(int, input().split()))

words_A = []
for i in range(A):
    words_A.append(input())
    lengths = [len(word) for word in words_A]
    if lengths == A:
        break


words_B = []
for j in range(B):
    words_B.append(input())
    lengths = [len(word) for word in words_B]
    if lengths == B:
        break

occs = defaultdict(list)
for i in words_B:
    count = 0
    z = 0
    for j in words_A:
        count += 1
        if i == j:
            occs[i].append(count)
            z = 1
    if z != 1:
        occs[i].append(-1)
        

for i in occs:
    print(' '.join(map(str, occs[i])))

## collections.namedtuple()

In [3]:
from collections import namedtuple
point = namedtuple('point', 'x, y')
pt1 = point(1, 2)
pt2 = point(3, 4)
pt1, pt2

(point(x=1, y=2), point(x=3, y=4))

In [14]:
from collections import namedtuple

input_ = int(input())
my_fields = input().split()
total_marks = 0

for _ in range(input_):
    students = namedtuple('my_student', my_fields)
    MARKS, CLASS, NAME, ID = input().split()
    my_student = students(MARKS, CLASS, NAME, ID)
    total_marks += int(my_student.MARKS)
    
print((total_marks / input_))

78.0


## collections.OrderedDict

In [25]:
from collections import OrderedDict
N = int(input())
Shopping_list = OrderedDict()

for _ in range(N):
     
    item_info = input().split()
    item_name = ' '.join(item_info[:-1])
    item_price = int(item_info[-1])

    if item_name in Shopping_list:
        Shopping_list[item_name] += item_price
        continue
    else:
        Shopping_list[item_name] = item_price 

for item_name, item_price in Shopping_list.items():
        print(item_name, item_price)

BANANA FRIES 12
POTATO CHIPS 60
APPLE JUICE 20
CANDY 20


## collections.deque()

In [39]:
# Perform append, pop, popleft and appendleft methods on an empty deque
from collections import deque

n = int(input())  # number of operations
d = deque()  

for i in range(n):
    operation = input().split()

    if operation[0] == 'append':
        d.append(int(operation[1]))

    elif operation[0] == 'pop':
        d.pop()

    elif operation[0] == 'popleft':
        d.popleft()

    elif operation[0] == 'appendleft':
        d.appendleft(int(operation[1]))

for i in d:
    print(i, end = ' ')

## Word Order

In [4]:
from collections import Counter,OrderedDict

ordered_dict = OrderedDict()
for i in range(int(input())):
    string = input()

    if string in ordered_dict:
        ordered_dict[string] += 1
    else:
        ordered_dict[string] = 1

print(len(ordered_dict.keys()))
print(*ordered_dict.values())

3
2 1 1


## Pilling Up!

In [67]:
from collections import deque
import math

t = int(input())
for i in range(t):
    ord = deque()
    n = int(input())
    l = list(map(int, input().split()))
    ord.extend(l)
    left = []
    right = []
    a = 0
    z = 0
    lenght = len(ord)
    if len(ord) % 2 == 0:
        a = 1

    for j in range(0, math.ceil(lenght / 2)):

        if a == 1:
            left.append(ord.popleft())
            right.append(ord.pop())
            if left[j] + right[j] > left + right[j-1]:
                print('No')
                z = 1
                break

        else:

            if j == math.ceil(lenght / 2) - 1:
                left.append(ord.popleft())
                if left[j] >= left[j-1] + right[j-1]:
                    print('No')
                    z = 1
                    break
            else:
                left.append(ord.popleft())
                right.append(ord.pop())
                if left[j] + right[j] > left[j-1] + right[j-1]:
                    print('No')
                    z = 1
                    break
        

    if z == 0:
        print('Yes')

No


In [68]:
num_test_cases = int(input())
for _ in range(num_test_cases):
    _ = int(input())
    list_blocks = deque(map(int, input().split(' ')))
    vertical_pile = []

    while len(list_blocks) > 0:
        if list_blocks[-1] > list_blocks[0]:
            block_removed = list_blocks.pop()
        else:
            block_removed = list_blocks.popleft()
        vertical_pile.append(block_removed)

    if all(vertical_pile[i] >= vertical_pile[i+1] for i in range(len(vertical_pile)-1)):
        print("Yes")
    else:
        print("No")


No


## Calendar Module

In [16]:
import calendar
m, d, y = input().split()
day = calendar.weekday(int(y), int(m), int(d))
class_names_days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
print(class_names_days[day].upper())

WEDNESDAY


## Exceptions

In [21]:
test_cases = int(input())
for i in range(test_cases):
    a, b = input().split()
    try:
        print(int(a)//int(b))
    except ValueError as v:
        print(f'Error Code: {v}')
    except ZeroDivisionError as e:
        print(f'Error Code: {e}')

Error Code: integer division or modulo by zero
Error Code: invalid literal for int() with base 10: '&'
3


## Incorrect Regex


In [7]:
import re

def is_valid_regex(pattern):
    try:
        re.compile(pattern)
        return True
    except re.error:
        return False
    
test_cases = int(input())
for i in range(test_cases):
    a = input()
    print(is_valid_regex(a))

True
False


## Zipped!

In [45]:
import pandas as pd
import numpy as np

n, s = input().split()
table = pd.DataFrame()

for i in range(int(s)):
    subject = list(map(float, input().split()))
    table[str(i)] = subject

a = np.average(table, axis=1)
for i in a:
    print(i)

90.0
91.0
82.0
90.0
85.5


## input()

In [65]:
x, k = input().split()
p = input()
p = p.replace('x', x)
if eval(p) == int(k):
    print(True)
else :
     print(False)

True


## Athlete Sort

In [8]:
#!/bin/python3

import math
import os
import random
import re
import sys


if __name__ == '__main__':
    n, m = input().split()

    n = int(n)

    m = int(m)

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    k = int(input())

    arr.sort(key = lambda x: x[k])

    for  i in arr:
        print(*i)

7 1 0
10 2 5
6 5 9
9 9 9
1 23 12


## Any or True

In [10]:
n = int(input())
nums = list(map(int, input().split()))
print(all([i > 0 for i in nums]) and any([str(i) == str(i)[::-1] for i in nums]))

True


## ginortS

In [84]:
string = input()

string_in_list = []
string_in_list.append([i for i in string if i.islower()])
l = []
for i in string_in_list:
    if i:
        l.append(''.join(i))
lower_sort = ''.join(sorted(l[0]))

string_in_list.clear()
string_in_list.append([i for i in string if i.isupper()])
l = []
for i in string_in_list:
    if i:
        l.append(''.join(i))
upper_sort = lower_sort + ''.join(sorted(l[0]))

string_in_list.clear()
digit = [i for i in string if i.isdigit()]
string_in_list.append([i for i in digit if int(i) % 2 != 0])
l = []
for i in string_in_list:
    if i:
        l.append(''.join(i))
odd_sort = ''.join(sorted(l[0]))
string_in_list.clear()
string_in_list.append([i for i in digit if int(i) % 2 == 0])
l = []
for i in string_in_list:
    if i:
        l.append(''.join(i))
odd_sort += ''.join(sorted(l[0]))

print(upper_sort+odd_sort)

abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1357902468


## Reduce Function

In [ ]:
from fractions import Fraction
from functools import reduce

def product(fracs):
    t = reduce(lambda x, y : x * y, fracs)
    return t.numerator, t.denominator

if __name__ == '__main__':
    fracs = []
    for _ in range(int(input())):
        fracs.append(Fraction(*map(int, input().split())))
    result = product(fracs)
    print(*result)

## Detect Floating Point

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from re import match, compile

pattern = compile('^[-+]?[0-9]*\.[0-9]+$')
for _ in range(int(input())):
    print(bool(pattern.match(input())))

## Re.Split()

In [3]:
regex_pattern = r"[.,]"	# Do not delete 'r'.

import re
print("\n".join(re.split(regex_pattern, input())))

1000
000
000
000


## Group(), Groups() & Groupdict()


In [7]:
m = re.match(r'(\w+)@(\w+)\.(\w+)','username@hackerrank.com')
m.group(0)

'username@hackerrank.com'

In [8]:
m.group(1)

'username'

In [9]:
m.group(1,2,3)

('username', 'hackerrank', 'com')

In [10]:
m.groups()

('username', 'hackerrank', 'com')

In [49]:
m = re.search(r'([a-zA-Z0-9])\1', input().strip())
print(m.group(1) if m else -1)

1


In [53]:
import re

# Read input and strip any leading/trailing whitespace
input_string = input().strip()

# Search for the first occurrence of any alphanumeric character followed by the same character
m = re.search(r'([a-zA-Z0-9])\1', input_string)

# If a match is found, return the matched string
if m:
    print(m.group(0))
else:
    print("No match found")

11


## Re.findall() & Re.finditer()

In [2]:
import re
string_input = input()
output = re.findall(r'(?<=[^aeiou])([aeiou]{2,})[^aeiou]', string_input, re.IGNORECASE)
if output:
    for i in output:
        print(i)
else:
    print(-1)

ee
Ioo
Oeo
eeeee


## validating phone number

In [3]:
import re
for i in range(int(input())):
    if re.match(r'[789]\d{9}$', input()):
        print('YES')
    else:
        print('NO')

YES
NO


## Re.start() & Re.end()

In [1]:
s = input()
k = input()
import re
pattern = re.compile(k)
r = pattern.search(s)
if not r:
    print('(-1, -1)')
while r:
    print(f'({r.start()}, {r.end() - 1})')
    r = pattern.search(s, r.start() + 1)

(0, 1)
(1, 2)
(4, 5)


## Regex Substitution

In [2]:
n = int(input())
for i in range(n):
    s = input()
    # replace all '&&' with 'and' and all '||' with 'or' with re.sub()
    s = re.sub(r'(?<= )(&&|\|\|)(?= )', lambda x: 'and' if x.group() == '&&' else 'or', s)
    print(s)

a = 1
b = input()

if a+b > 0 and a-b < 0 :
start()
#Note do not change &&& or ||| or & or |
#Only change those '&&' which have space on both sides.
#Only change those '|| which have space on both sides.





## Validating Roman Numerals


In [19]:
# i v x l c d m
import re
s = input()
m = re.match(r'^(?=[MDCLXVI])M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$', s)

print(bool(m))

False


## Validating and Parsing Email Addresses


In [1]:
import re
pattern = r'^<[A-Za-z](\w|-|\.|_)+@[A-Za-z]+\.[A-Za-z]{1,3}>$'
for _ in range(int(input())):
    name, email = input().split(' ')
    if re.match(pattern, email):
        print(name, email)

DEXTER <dexter@hotmail.com>


## Hex Color Code


In [2]:
import re
for _ in range(int(input())):
    matches = re.findall(r':?.(#[0-9a-fA-F]{6}|#[0-9a-fA-F]{3})', input())
    if matches:
        print(*matches, sep='\n')

#FfFdF8
#aef
#f9f9f9
#fff
#ABC
#fff


## HTML Parser - Part 1


In [3]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print ('Start :', tag)
        for ele in attrs:
            print ('->', ele[0], '>', ele[1])

    def handle_endtag(self, tag):
        print ('End   :', tag)
        
    def handle_startendtag(self, tag, attrs):
        print ('Empty :', tag)
        for ele in attrs:
            print ('->', ele[0], '>', ele[1])

parser = MyHTMLParser()
for _ in range(int(input())):
    parser.feed(input())

Start : html
Start : head
Start : title
End   : title
End   : head
Start : body
-> data-modal-target > None
-> class > 1
Start : h1
End   : h1
Empty : br
End   : body
End   : html


## HTML Parser - Part 2


In [4]:
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_comment(self, comment):
        if '\n' in comment:
            print('>>> Multi-line Comment')
        else:
            print('>>> Single-line Comment')

        print(comment)

    def handle_data(self, data):
        if data == '\n': return
        print('>>> Data')
        print(data)    
        
html = ""       
for i in range(int(input())):
    html += input().rstrip()
    html += '\n'
    
parser = MyHTMLParser()
parser.feed(html)
parser.close()

>>> Multi-line Comment
[if IE 9]>IE9-specific content
<![endif]
>>> Data
 Welcome to HackerRank
>>> Single-line Comment
[if IE 9]>IE9-specific content<![endif]


## Detect HTML Tags, Attributes and Attribute Values


In [5]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print(tag)
        [print('-> {} > {}'.format(*attr)) for attr in attrs]
        
html = '\n'.join([input() for _ in range(int(input()))])
parser = MyHTMLParser()
parser.feed(html)
parser.close()

head
title
object
-> type > application/x-flash
-> data > your-file.swf
-> width > 0
-> height > 0
param
-> name > quality
-> value > high


## Validating UID

In [6]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import re

for _ in range(int(input())):
    u = ''.join(sorted(input()))
    try:
        assert re.search(r'[A-Z]{2}', u)
        assert re.search(r'\d\d\d', u)
        assert not re.search(r'[^a-zA-Z0-9]', u)
        assert not re.search(r'(.)\1', u)
        assert len(u) == 10
    except:
        print('Invalid')
    else:
        print('Valid')

Invalid
Valid


## Validating Credit Card Numbers


In [7]:
import re

def is_valid_credit_card(card_number):
    pattern = r'^[456]\d{3}(-?\d{4}){3}$'
    match = re.match(pattern, card_number)
    if match:
        card_number = card_number.replace('-', '')
        for i in range(len(card_number) - 3):
            if card_number[i] == card_number[i + 1] == card_number[i + 2] == card_number[i + 3]:
                return False
        return True
    return False

n = int(input())
for _ in range(n):
    card_number = input()
    if is_valid_credit_card(card_number):
        print("Valid")
    else:
        print("Invalid")

Valid
Valid
Invalid
Valid
Invalid
Invalid


## Arrays

In [20]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    nums = numpy.array(arr)

    l = []
    for i in range(len(nums), 0, -1):
        l.append(nums[i-1])
    nums = numpy.array(l, dtype=float)
    return nums

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

[-10.  -8.   4.   3.   2.   1.]


## Shape and Reshape

In [25]:
import numpy as np

nums = list(map(int, input().split()))

print(np.array(nums).reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Transpose and Flatten

In [27]:
import numpy as np

n, m = map(int, input().split())
a = np.array([input().split() for _ in range(n)], int)
print(a.transpose())
print(a.flatten())

[[1 1]
 [2 2]
 [3 3]]
[1 2 3 1 2 3]


## Concatenate

In [28]:
import numpy as np
n,m,p = map(int, input().split())
a=np.array([input().split() for _ in range(n)],int)

b=np.array([input().split() for _ in range(m)],int)

print(np.concatenate((a,b),axis=0))


[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## Zeros and Ones

In [52]:
import numpy as np

def create_arrays():
    # Read space-separated integers as shape
    shape = tuple(map(int, input().split()))
    # Create and print arrays
    print(np.zeros(shape, dtype=int))
    print(np.ones(shape, dtype=int))

create_arrays()

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## Eye and Identity

In [53]:
import numpy as np
np.set_printoptions(legacy='1.13')
n,m = map(int,input().split())
print(np.eye(n,m))


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
